export const restaurants = [
	{
		id: 1,
		name: "restaurant1",
		type: "Family Style",
		rating: 3,
		coordinates: [51.505, -0.09],
	},
	{
		id: 2,
		name: "restaurant2",
		type: "Fast Food",
		rating: 3,
		coordinates: [51.605, -0.1],
	},
	{
		id: 3,
		name: "restaurant3",
		type: "Buffet",
		rating: 4,
		coordinates: [51.805, -0.29],
	},
	{
		id: 4,
		name: "restaurant4",
		type: "Family Style",
		rating: 5,
		coordinates: [51.005, -1.0],
	},
	{
		id: 5,
		name: "restaurant5",
		type: "Fast Food",
		rating: 5,
		coordinates: [51.505, 0.59],
	},
	{
		id: 6,
		name: "restaurant6",
		type: "Cafe",
		rating: 3,
		coordinates: [51.205, -0.29],
	},
	{
		id: 7,
		name: "restaurant7",
		type: "Buffet",
		rating: 1,
		coordinates: [51.705, -0.79],
	},
];
