module.exports = [
  {
    name: "admin",
    email: "admin@gmail.com",
    password: "admin",
    created_at: null,
    updated_at: null,
    location_created_at: "",
    location_current: "",
    profile_image_url: "",
  },
  {
    name: "Cristian",
    email: "Cristian.Niculescu@gmail.com",
    password: "1234",
    created_at: null,
    updated_at: null,
    location_created_at: "",
    location_current: "",
    profile_image_url: "",
  },
  {
    name: "Brian",
    email: "Brian.Bird@gmail.com",
    password: "1234",
    created_at: null,
    updated_at: null,
    location_created_at: "",
    location_current: "",
    profile_image_url: "",
  },
];
